window.RECIPES = [...(window.RECIPES || []),
  {
    id: "speedy-satay-chicken",
    title: "Speedy Satay Chicken",
    summary: "A fast one-pan chicken mince satay with creamy coconut-peanut sauce, hidden grated veg and rice. Proper school-night fakeaway territory.",
    category: "One-pot",
    tags: ["Chicken", "One-pot", "Quick", "School night", "Hidden veg", "Asian-style", "Fakeaway"],
    serves: "4",
    prep: "10 mins",
    cook: "15 mins",
    made: false,
    archive: false,
    photo: "",
    photoAlt: "Speedy satay chicken with rice and fresh toppings",
    photoStatus: "Ready to try",
    source: "Adapted from Simple Home Edit - Speedy Satay Chicken",
    sourceUrl: "https://simplehomeedit.com/recipe/speedy-satay-chicken/",
    ingredients: [
      "500 g chicken mince",
      "1 onion, finely diced",
      "2 garlic cloves, finely chopped",
      "1 carrot, very finely grated",
      "1 small courgette, very finely grated and lightly squeezed",
      "1 tbsp mild curry powder",
      "½ tsp ground turmeric",
      "1 tsp sweet paprika",
      "400 ml coconut milk",
      "125 ml chicken stock",
      "90 g smooth peanut butter",
      "1 tbsp kecap manis or sweet soy sauce",
      "1 tsp dark soy sauce",
      "1 tsp brown sugar",
      "250 g jasmine rice, cooked to serve",
      "2 small cucumbers, sliced",
      "¼ red onion, finely sliced",
      "40 g crushed peanuts",
      "Fresh coriander, optional",
      "1 lime",
      "Chilli oil, optional"
    ],
    shopping: [
      { item: "Chicken mince", qty: 500, unit: "g", category: "Meat & fish" },
      { item: "Onions", qty: 1, unit: "", category: "Fruit & veg" },
      { item: "Red onions", qty: 0.25, unit: "", category: "Fruit & veg" },
      { item: "Garlic cloves", qty: 2, unit: "", category: "Fruit & veg" },
      { item: "Carrots", qty: 1, unit: "", category: "Fruit & veg" },
      { item: "Courgettes", qty: 1, unit: "", category: "Fruit & veg" },
      { item: "Cucumbers", qty: 2, unit: "", category: "Fruit & veg" },
      { item: "Limes", qty: 1, unit: "", category: "Fruit & veg" },
      { item: "Fresh coriander", qty: null, unit: "", category: "Fruit & veg" },
      { item: "Coconut milk", qty: 400, unit: "ml", category: "Tins & jars" },
      { item: "Smooth peanut butter", qty: 90, unit: "g", category: "Pantry" },
      { item: "Kecap manis or sweet soy sauce", qty: 1, unit: "tbsp", category: "Pantry" },
      { item: "Dark soy sauce", qty: 1, unit: "tsp", category: "Pantry" },
      { item: "Chicken stock", qty: 125, unit: "ml", category: "Pantry" },
      { item: "Brown sugar", qty: 1, unit: "tsp", category: "Pantry" },
      { item: "Jasmine rice", qty: 250, unit: "g", category: "Pasta, rice & grains" },
      { item: "Crushed peanuts", qty: 40, unit: "g", category: "Pantry" },
      { item: "Mild curry powder", qty: 1, unit: "tbsp", category: "Herbs & spices" },
      { item: "Ground turmeric", qty: 0.5, unit: "tsp", category: "Herbs & spices" },
      { item: "Sweet paprika", qty: 1, unit: "tsp", category: "Herbs & spices" }
    ],
    method: [
      "Whisk together the coconut milk, chicken stock, peanut butter, kecap manis and dark soy until smooth.",
      "Heat a large frying pan over medium-high heat with a little neutral oil. Soften the onion and garlic for 2 minutes.",
      "Add the chicken mince and cook for 3 to 4 minutes, breaking it into chunky pieces rather than very fine crumbs.",
      "Stir in the grated carrot and courgette, curry powder, turmeric, paprika and brown sugar. Cook for another 2 minutes so the veg softens into the mince.",
      "Pour in the satay sauce. Simmer uncovered for 4 to 6 minutes, stirring regularly, until glossy and thick enough to coat the chicken. If it looks loose, give it another couple of minutes in a wide pan.",
      "Serve over hot jasmine rice with cucumber, red onion, crushed peanuts, coriander and plenty of lime. Keep chilli oil on the table for the grown-ups."
    ],
    note: "Adapted from Nicole Maguire's Speedy Satay Chicken at Simple Home Edit. We've added finely grated carrot and courgette for the Langton-Cox hidden-veg treatment."
  }
];