window.RECIPES = [...(window.RECIPES || []),
  {
    id: "chicken-shawarma-rice-traybake",
    title: "Chicken Shawarma Rice Traybake",
    summary: "Warm spiced chicken, peppers and rice cooked together with lemon and yoghurt on the side. Big flavour without a long ingredient list.",
    category: "Traybake",
    tags: ["Chicken", "Rice", "Traybake", "School night", "Middle Eastern-style"],
    serves: "4",
    prep: "15 mins",
    cook: "40 mins",
    made: false,
    archive: false,
    photo: "",
    photoAlt: "Chicken shawarma rice traybake",
    photoStatus: "Ready to try",
    ingredients: ["600 g chicken thighs, sliced", "250 g basmati rice", "1 red pepper, sliced", "1 onion, sliced", "2 garlic cloves", "1 tsp cumin", "1 tsp paprika", "1 tsp ground coriander", "½ tsp turmeric", "600 ml chicken stock", "1 lemon", "150 g Greek yoghurt"],
    shopping: [
      { item: "Chicken thighs", qty: 600, unit: "g", category: "Meat & fish" },
      { item: "Basmati rice", qty: 250, unit: "g", category: "Pasta, rice & grains" },
      { item: "Red peppers", qty: 1, unit: "", category: "Fruit & veg" },
      { item: "Onions", qty: 1, unit: "", category: "Fruit & veg" },
      { item: "Garlic cloves", qty: 2, unit: "", category: "Fruit & veg" },
      { item: "Lemons", qty: 1, unit: "", category: "Fruit & veg" },
      { item: "Greek yoghurt", qty: 150, unit: "g", category: "Dairy & eggs" },
      { item: "Chicken stock", qty: 600, unit: "ml", category: "Pantry" },
      { item: "Ground cumin", qty: 1, unit: "tsp", category: "Herbs & spices" },
      { item: "Paprika", qty: 1, unit: "tsp", category: "Herbs & spices" },
      { item: "Ground coriander", qty: 1, unit: "tsp", category: "Herbs & spices" },
      { item: "Turmeric", qty: 0.5, unit: "tsp", category: "Herbs & spices" }
    ],
    method: ["Heat the oven to 210°C. Toss the chicken with cumin, paprika, coriander, turmeric, salt and a little oil.", "Spread the rice, pepper, onion and garlic in a deep roasting dish and pour over the hot stock.", "Lay the chicken over the top, cover tightly with foil and bake for 25 minutes.", "Remove the foil and bake for another 12 to 15 minutes until the chicken is cooked and the rice is tender.", "Finish with lemon juice and serve with yoghurt."],
    note: "A good midweek bridge between familiar chicken-and-rice and something a bit more interesting."
  },
  {
    id: "honey-mustard-chicken-potatoes",
    title: "Honey Mustard Chicken & Potatoes",
    summary: "Sticky mustard chicken with baby potatoes, carrots and green beans on one tray. Sweet enough for the boys, sharp enough not to be boring.",
    category: "Traybake",
    tags: ["Chicken", "Traybake", "School night", "Family dinner"],
    serves: "4",
    prep: "15 mins",
    cook: "45 mins",
    made: false,
    archive: false,
    photo: "",
    photoAlt: "Honey mustard chicken and potatoes",
    photoStatus: "Ready to try",
    ingredients: ["4 chicken breasts", "700 g baby potatoes, halved", "3 carrots, cut into batons", "150 g green beans", "2 tbsp Dijon mustard", "2 tbsp honey", "1 tbsp olive oil", "2 garlic cloves", "1 tsp dried thyme", "½ lemon"],
    shopping: [
      { item: "Chicken breasts", qty: 4, unit: "", category: "Meat & fish" },
      { item: "Baby potatoes", qty: 700, unit: "g", category: "Fruit & veg" },
      { item: "Carrots", qty: 3, unit: "", category: "Fruit & veg" },
      { item: "Green beans", qty: 150, unit: "g", category: "Fruit & veg" },
      { item: "Garlic cloves", qty: 2, unit: "", category: "Fruit & veg" },
      { item: "Lemons", qty: 0.5, unit: "", category: "Fruit & veg" },
      { item: "Dijon mustard", qty: 2, unit: "tbsp", category: "Pantry" },
      { item: "Honey", qty: 2, unit: "tbsp", category: "Pantry" },
      { item: "Dried thyme", qty: 1, unit: "tsp", category: "Herbs & spices" }
    ],
    method: ["Heat the oven to 210°C. Toss the potatoes and carrots with oil, thyme, salt and pepper and roast for 20 minutes.", "Mix the mustard, honey, garlic and lemon juice.", "Add the chicken to the tray, brush generously with the honey mustard glaze and roast for 18 minutes.", "Add the green beans, brush the chicken again and roast for a final 7 to 10 minutes until cooked through."],
    note: "Cut thick chicken breasts in half horizontally if you want this closer to a 35-minute dinner."
  },
  {
    id: "beef-enchilada-rice-bake",
    title: "Hidden-Veg Beef Enchilada Rice Bake",
    summary: "Beef, rice, beans and cheese with carrot and pepper blended into the tomato sauce. Taco-night energy with less table assembly.",
    category: "One-pot",
    tags: ["Beef", "Rice", "Fajitas & tacos", "Hidden veg", "School night"],
    serves: "5",
    prep: "20 mins",
    cook: "35 mins",
    made: false,
    archive: false,
    photo: "",
    photoAlt: "Beef enchilada rice bake",
    photoStatus: "Ready to try",
    ingredients: ["500 g beef mince", "1 onion", "1 carrot", "1 red pepper", "2 garlic cloves", "1 x 400 g tin chopped tomatoes", "1 tbsp tomato purée", "1 tsp cumin", "2 tsp smoked paprika", "250 g long-grain rice", "500 ml beef stock", "1 x 400 g tin black beans, drained", "150 g cheddar"],
    shopping: [
      { item: "Beef mince", qty: 500, unit: "g", category: "Meat & fish" },
      { item: "Onions", qty: 1, unit: "", category: "Fruit & veg" },
      { item: "Carrots", qty: 1, unit: "", category: "Fruit & veg" },
      { item: "Red peppers", qty: 1, unit: "", category: "Fruit & veg" },
      { item: "Garlic cloves", qty: 2, unit: "", category: "Fruit & veg" },
      { item: "Chopped tomatoes", qty: 1, unit: "400 g tin", category: "Tins & jars" },
      { item: "Black beans", qty: 1, unit: "400 g tin", category: "Tins & jars" },
      { item: "Long-grain rice", qty: 250, unit: "g", category: "Pasta, rice & grains" },
      { item: "Cheddar", qty: 150, unit: "g", category: "Dairy & eggs" },
      { item: "Beef stock", qty: 500, unit: "ml", category: "Pantry" },
      { item: "Tomato purée", qty: 1, unit: "tbsp", category: "Pantry" },
      { item: "Ground cumin", qty: 1, unit: "tsp", category: "Herbs & spices" },
      { item: "Smoked paprika", qty: 2, unit: "tsp", category: "Herbs & spices" }
    ],
    method: ["Cook the carrot and pepper with the chopped tomatoes for 8 minutes, then blend smooth.", "Brown the beef with the onion. Add garlic, cumin and paprika.", "Stir in the rice, blended sauce, tomato purée and stock. Cover and simmer gently for 18 minutes.", "Fold through the black beans, scatter over the cheddar and grill or bake until bubbling."],
    note: "Serve with tortilla chips, yoghurt or sour cream if you want the full Friday-night treatment."
  },
  {
    id: "one-pot-cheeseburger-pasta",
    title: "One-Pot Cheeseburger Pasta",
    summary: "Beefy, cheesy and extremely child-friendly, with grated carrot and courgette melting into the sauce while nobody is looking.",
    category: "One-pot",
    tags: ["Beef", "Pasta", "One-pot", "Hidden veg", "School night"],
    serves: "5",
    prep: "15 mins",
    cook: "30 mins",
    made: false,
    archive: false,
    photo: "",
    photoAlt: "One pot cheeseburger pasta",
    photoStatus: "Ready to try",
    ingredients: ["500 g beef mince", "1 onion, finely diced", "1 carrot, finely grated", "1 small courgette, finely grated", "2 tbsp tomato purée", "1 tsp mustard", "750 ml beef stock", "300 g short pasta", "120 g cheddar", "1 tsp smoked paprika", "Pickles to serve, optional"],
    shopping: [
      { item: "Beef mince", qty: 500, unit: "g", category: "Meat & fish" },
      { item: "Onions", qty: 1, unit: "", category: "Fruit & veg" },
      { item: "Carrots", qty: 1, unit: "", category: "Fruit & veg" },
      { item: "Courgettes", qty: 1, unit: "", category: "Fruit & veg" },
      { item: "Short pasta", qty: 300, unit: "g", category: "Pasta, rice & grains" },
      { item: "Cheddar", qty: 120, unit: "g", category: "Dairy & eggs" },
      { item: "Beef stock", qty: 750, unit: "ml", category: "Pantry" },
      { item: "Tomato purée", qty: 2, unit: "tbsp", category: "Pantry" },
      { item: "Mustard", qty: 1, unit: "tsp", category: "Pantry" },
      { item: "Smoked paprika", qty: 1, unit: "tsp", category: "Herbs & spices" }
    ],
    method: ["Brown the mince well in a large deep pan, then add the onion, carrot and courgette and cook until softened.", "Stir in the tomato purée, mustard and paprika.", "Add the pasta and stock. Simmer uncovered, stirring regularly, until the pasta is tender and the sauce has thickened.", "Take off the heat and stir through most of the cheddar. Scatter the rest over the top and cover for 2 minutes to melt."],
    note: "A useful emergency-school-night recipe because there is only one pan and the veg has nowhere to stage a protest."
  },
  {
    id: "chicken-pesto-hidden-veg-pasta",
    title: "Chicken Pesto Hidden-Veg Pasta",
    summary: "Chicken, pasta and pesto with spinach and courgette blended straight into the sauce. Green, yes, but smooth enough to avoid leafy evidence.",
    category: "Pasta",
    tags: ["Chicken", "Pasta", "Hidden veg", "School night", "Quick"],
    serves: "4",
    prep: "15 mins",
    cook: "25 mins",
    made: false,
    archive: false,
    photo: "",
    photoAlt: "Chicken pesto hidden veg pasta",
    photoStatus: "Ready to try",
    ingredients: ["500 g chicken breast, diced", "350 g pasta", "1 small courgette, chopped", "100 g baby spinach", "120 g pesto", "100 ml chicken stock", "50 g Parmesan", "1 garlic clove", "½ lemon"],
    shopping: [
      { item: "Chicken breast", qty: 500, unit: "g", category: "Meat & fish" },
      { item: "Pasta", qty: 350, unit: "g", category: "Pasta, rice & grains" },
      { item: "Courgettes", qty: 1, unit: "", category: "Fruit & veg" },
      { item: "Baby spinach", qty: 100, unit: "g", category: "Fruit & veg" },
      { item: "Garlic cloves", qty: 1, unit: "", category: "Fruit & veg" },
      { item: "Lemons", qty: 0.5, unit: "", category: "Fruit & veg" },
      { item: "Pesto", qty: 120, unit: "g", category: "Tins & jars" },
      { item: "Parmesan", qty: 50, unit: "g", category: "Dairy & eggs" },
      { item: "Chicken stock", qty: 100, unit: "ml", category: "Pantry" }
    ],
    method: ["Cook the pasta until al dente, reserving a mug of pasta water.", "Brown the chicken in a large frying pan and season well.", "Simmer the courgette, spinach, garlic and stock for 5 minutes, then blend smooth with the pesto and lemon juice.", "Pour the sauce over the chicken, add the pasta and toss with Parmesan. Loosen with pasta water as needed."],
    note: "If the boys object to visibly green sauce, use half the spinach the first time and increase it later. Stealth has a learning curve."
  },
  {
    id: "lamb-taco-bowls",
    title: "Lamb Taco Bowls",
    summary: "Spiced lamb mince, rice, corn, cheese and crunchy toppings in build-your-own bowls. Taco night without the tortilla structural engineering.",
    category: "Bowls",
    tags: ["Lamb", "Fajitas & tacos", "Rice", "Family dinner", "Friday"],
    serves: "4",
    prep: "20 mins",
    cook: "25 mins",
    made: false,
    archive: false,
    photo: "",
    photoAlt: "Lamb taco bowls",
    photoStatus: "Ready to try",
    ingredients: ["500 g lamb mince", "250 g basmati rice", "1 onion, diced", "1 red pepper, finely diced", "1 tsp cumin", "1 tsp smoked paprika", "½ tsp oregano", "150 g sweetcorn", "100 g cheddar", "1 lime", "Salsa, yoghurt and tortilla chips to serve"],
    shopping: [
      { item: "Lamb mince", qty: 500, unit: "g", category: "Meat & fish" },
      { item: "Basmati rice", qty: 250, unit: "g", category: "Pasta, rice & grains" },
      { item: "Onions", qty: 1, unit: "", category: "Fruit & veg" },
      { item: "Red peppers", qty: 1, unit: "", category: "Fruit & veg" },
      { item: "Limes", qty: 1, unit: "", category: "Fruit & veg" },
      { item: "Sweetcorn", qty: 150, unit: "g", category: "Tins & jars" },
      { item: "Cheddar", qty: 100, unit: "g", category: "Dairy & eggs" },
      { item: "Salsa", qty: 1, unit: "jar", category: "Tins & jars" },
      { item: "Greek yoghurt", qty: 150, unit: "g", category: "Dairy & eggs" },
      { item: "Tortilla chips", qty: 1, unit: "bag", category: "Bakery" },
      { item: "Ground cumin", qty: 1, unit: "tsp", category: "Herbs & spices" },
      { item: "Smoked paprika", qty: 1, unit: "tsp", category: "Herbs & spices" }
    ],
    method: ["Cook the rice and keep warm.", "Brown the lamb mince thoroughly, then add onion and pepper and cook until soft.", "Stir in cumin, paprika and oregano with a splash of water and cook for 2 minutes.", "Add the sweetcorn and lime juice.", "Build bowls with rice, lamb, cheese, salsa, yoghurt and crushed tortilla chips."],
    note: "Good for different appetites because everyone can build their own bowl without needing four separate dinners."
  },
  {
    id: "mild-chicken-tikka-rice-pot",
    title: "Mild Chicken Tikka Rice Pot",
    summary: "A gentle tomato-yoghurt chicken rice pot with hidden carrot and pepper. Curry-night flavour without making the boys regret sitting down.",
    category: "One-pot",
    tags: ["Chicken", "Rice", "One-pot", "Hidden veg", "School night", "Curry"],
    serves: "4",
    prep: "20 mins",
    cook: "35 mins",
    made: false,
    archive: false,
    photo: "",
    photoAlt: "Mild chicken tikka rice pot",
    photoStatus: "Ready to try",
    ingredients: ["600 g chicken breast, diced", "150 g Greek yoghurt", "2 tsp mild curry powder", "1 tsp paprika", "1 carrot, chopped", "1 red pepper, chopped", "1 onion", "2 garlic cloves", "1 x 400 g tin chopped tomatoes", "250 g basmati rice", "450 ml chicken stock", "75 g frozen peas"],
    shopping: [
      { item: "Chicken breast", qty: 600, unit: "g", category: "Meat & fish" },
      { item: "Greek yoghurt", qty: 150, unit: "g", category: "Dairy & eggs" },
      { item: "Carrots", qty: 1, unit: "", category: "Fruit & veg" },
      { item: "Red peppers", qty: 1, unit: "", category: "Fruit & veg" },
      { item: "Onions", qty: 1, unit: "", category: "Fruit & veg" },
      { item: "Garlic cloves", qty: 2, unit: "", category: "Fruit & veg" },
      { item: "Chopped tomatoes", qty: 1, unit: "400 g tin", category: "Tins & jars" },
      { item: "Basmati rice", qty: 250, unit: "g", category: "Pasta, rice & grains" },
      { item: "Frozen peas", qty: 75, unit: "g", category: "Frozen" },
      { item: "Chicken stock", qty: 450, unit: "ml", category: "Pantry" },
      { item: "Mild curry powder", qty: 2, unit: "tsp", category: "Herbs & spices" },
      { item: "Paprika", qty: 1, unit: "tsp", category: "Herbs & spices" }
    ],
    method: ["Mix the chicken with half the yoghurt, curry powder and paprika and leave while you prep everything else.", "Cook the carrot and red pepper in the chopped tomatoes for 8 minutes, then blend smooth.", "Brown the chicken in a wide lidded pan, then add onion and garlic.", "Stir in the rice, blended sauce and stock. Cover and simmer for 18 minutes.", "Add the peas for the final 3 minutes and stir through the remaining yoghurt off the heat."],
    note: "Keep chilli off the base recipe and add it at the table. That makes this one family dinner rather than two parallel diplomatic negotiations."
  },
  {
    id: "beef-ragu-hidden-veg",
    title: "Slow Beef Ragu with Hidden Veg",
    summary: "A richer weekend beef ragu with carrot, celery, courgette and mushrooms disappearing into the sauce during a long simmer.",
    category: "Slow cook",
    tags: ["Beef", "Pasta", "Hidden veg", "Weekend", "Slow cook"],
    serves: "6",
    prep: "25 mins",
    cook: "2½ hours",
    made: false,
    archive: false,
    photo: "",
    photoAlt: "Slow beef ragu with hidden vegetables",
    photoStatus: "Ready to try",
    ingredients: ["800 g stewing beef or beef mince", "1 onion", "2 carrots", "2 celery sticks", "1 courgette", "150 g mushrooms", "3 garlic cloves", "2 tbsp tomato purée", "2 x 400 g tins chopped tomatoes", "300 ml beef stock", "1 tsp oregano", "500 g pappardelle or rigatoni", "Parmesan to serve"],
    shopping: [
      { item: "Stewing beef", qty: 800, unit: "g", category: "Meat & fish" },
      { item: "Onions", qty: 1, unit: "", category: "Fruit & veg" },
      { item: "Carrots", qty: 2, unit: "", category: "Fruit & veg" },
      { item: "Celery sticks", qty: 2, unit: "", category: "Fruit & veg" },
      { item: "Courgettes", qty: 1, unit: "", category: "Fruit & veg" },
      { item: "Mushrooms", qty: 150, unit: "g", category: "Fruit & veg" },
      { item: "Garlic cloves", qty: 3, unit: "", category: "Fruit & veg" },
      { item: "Chopped tomatoes", qty: 2, unit: "400 g tin", category: "Tins & jars" },
      { item: "Pappardelle or rigatoni", qty: 500, unit: "g", category: "Pasta, rice & grains" },
      { item: "Parmesan", qty: 80, unit: "g", category: "Dairy & eggs" },
      { item: "Beef stock", qty: 300, unit: "ml", category: "Pantry" },
      { item: "Tomato purée", qty: 2, unit: "tbsp", category: "Pantry" },
      { item: "Dried oregano", qty: 1, unit: "tsp", category: "Herbs & spices" }
    ],
    method: ["Blitz the onion, carrots, celery, courgette and mushrooms very finely in a food processor.", "Brown the beef deeply in batches, then remove.", "Cook the blitzed vegetables for 10 to 12 minutes until soft and reduced. Add garlic and tomato purée.", "Return the beef, add tomatoes, stock and oregano, then simmer very gently for around 2 hours until rich and tender.", "Shred the beef if using chunks, then toss with pasta and Parmesan."],
    note: "This is a weekend one because time does the work. It also freezes brilliantly, so making six portions earns future school-night credit."
  }
];
