window.RECIPES = [...(window.RECIPES || []),
  {
    id: "lemon-herb-chicken-rice",
    title: "One-Pan Lemon Herb Chicken & Rice",
    summary: "Golden chicken over lemony rice with grated carrot and courgette disappearing into the pan. Built for a school night.",
    category: "One-pot",
    tags: ["Chicken", "One-pot", "School night", "Rice", "Hidden veg"],
    serves: "4",
    prep: "15 mins",
    cook: "35 mins",
    made: false,
    archive: false,
    photo: "",
    photoAlt: "Lemon herb chicken and rice",
    photoStatus: "Ready to try",
    ingredients: [
      "4 chicken breasts or 6 boneless chicken thighs",
      "1 tbsp olive oil",
      "1 tsp dried oregano",
      "1 tsp paprika",
      "1 onion, finely diced",
      "2 garlic cloves, chopped",
      "1 carrot, finely grated",
      "1 small courgette, finely grated",
      "250 g basmati rice, rinsed",
      "600 ml chicken stock",
      "1 lemon, zest and juice",
      "75 g frozen peas",
      "Salt and black pepper"
    ],
    shopping: [
      { item: "Chicken breasts", qty: 4, unit: "", category: "Meat & fish" },
      { item: "Onions", qty: 1, unit: "", category: "Fruit & veg" },
      { item: "Garlic cloves", qty: 2, unit: "", category: "Fruit & veg" },
      { item: "Carrots", qty: 1, unit: "", category: "Fruit & veg" },
      { item: "Courgettes", qty: 1, unit: "", category: "Fruit & veg" },
      { item: "Lemons", qty: 1, unit: "", category: "Fruit & veg" },
      { item: "Frozen peas", qty: 75, unit: "g", category: "Frozen" },
      { item: "Basmati rice", qty: 250, unit: "g", category: "Pasta, rice & grains" },
      { item: "Chicken stock", qty: 600, unit: "ml", category: "Pantry" },
      { item: "Dried oregano", qty: 1, unit: "tsp", category: "Herbs & spices" },
      { item: "Paprika", qty: 1, unit: "tsp", category: "Herbs & spices" }
    ],
    method: [
      "Season the chicken with oregano, paprika, salt and pepper. Brown in the oil for 3 to 4 minutes per side, then lift out.",
      "Lower the heat and cook the onion for 4 minutes. Add garlic, grated carrot and courgette and cook until the vegetables soften and lose most of their moisture.",
      "Stir in the rice, then add the stock and lemon zest. Bring to a simmer.",
      "Nestle the chicken back on top, cover and cook gently for about 18 minutes, or until the rice is tender and the chicken is cooked through.",
      "Stir the peas through the rice for the final 3 minutes. Finish with lemon juice and black pepper."
    ],
    note: "Grate the carrot and courgette very finely. Once they cook into the rice, they become background flavour rather than visible vegetables."
  },
  {
    id: "chicken-fajita-traybake",
    title: "Chicken Fajita Traybake",
    summary: "Everything that makes fajitas popular, but tipped onto one tray. Chicken, peppers, onions and warm tortillas with very little washing up.",
    category: "Traybake",
    tags: ["Chicken", "Fajitas & tacos", "School night", "Traybake", "Mexican-style"],
    serves: "4",
    prep: "15 mins",
    cook: "25 mins",
    made: false,
    archive: false,
    photo: "",
    photoAlt: "Chicken fajita traybake",
    photoStatus: "Ready to try",
    ingredients: [
      "600 g chicken breast, sliced",
      "2 peppers, sliced",
      "1 large onion, sliced",
      "2 tbsp olive oil",
      "2 tsp smoked paprika",
      "1 tsp ground cumin",
      "1 tsp dried oregano",
      "1 tsp garlic powder",
      "1 lime",
      "8 small flour tortillas",
      "Sour cream, grated cheese and salsa to serve"
    ],
    shopping: [
      { item: "Chicken breast", qty: 600, unit: "g", category: "Meat & fish" },
      { item: "Peppers", qty: 2, unit: "", category: "Fruit & veg" },
      { item: "Onions", qty: 1, unit: "", category: "Fruit & veg" },
      { item: "Limes", qty: 1, unit: "", category: "Fruit & veg" },
      { item: "Flour tortillas", qty: 8, unit: "", category: "Bakery" },
      { item: "Sour cream", qty: 1, unit: "tub", category: "Dairy & eggs" },
      { item: "Grated cheese", qty: 150, unit: "g", category: "Dairy & eggs" },
      { item: "Salsa", qty: 1, unit: "jar", category: "Tins & jars" },
      { item: "Smoked paprika", qty: 2, unit: "tsp", category: "Herbs & spices" },
      { item: "Ground cumin", qty: 1, unit: "tsp", category: "Herbs & spices" }
    ],
    method: [
      "Heat the oven to 220°C. Toss the chicken, peppers and onion with oil, paprika, cumin, oregano, garlic powder, salt and pepper.",
      "Spread everything in a single layer on a large tray. Roast for 18 to 22 minutes, turning once, until the chicken is cooked and the edges of the vegetables are catching.",
      "Squeeze lime juice over the tray.",
      "Warm the tortillas for the final few minutes, then let everyone build their own fajitas with cheese, sour cream and salsa."
    ],
    note: "For the boys, keep some chicken plain-ish at one end of the tray if needed. The build-your-own format usually does half the negotiating for you."
  },
  {
    id: "hidden-veg-chicken-fajita-rice",
    title: "Hidden-Veg Chicken Fajita Rice Pot",
    summary: "Fajita flavours in a one-pot rice dinner, with carrot and red pepper blended into the tomato base before anyone can lodge a complaint.",
    category: "One-pot",
    tags: ["Chicken", "Fajitas & tacos", "One-pot", "Rice", "Hidden veg", "School night"],
    serves: "4",
    prep: "15 mins",
    cook: "35 mins",
    made: false,
    archive: false,
    photo: "",
    photoAlt: "Chicken fajita rice pot",
    photoStatus: "Ready to try",
    ingredients: [
      "600 g chicken breast, diced",
      "1 onion, finely diced",
      "1 carrot, chopped",
      "1 red pepper, chopped",
      "2 garlic cloves",
      "1 tbsp tomato purée",
      "1 x 400 g tin chopped tomatoes",
      "2 tsp smoked paprika",
      "1 tsp ground cumin",
      "250 g basmati rice, rinsed",
      "450 ml chicken stock",
      "100 g sweetcorn",
      "1 lime",
      "Grated cheddar to serve"
    ],
    shopping: [
      { item: "Chicken breast", qty: 600, unit: "g", category: "Meat & fish" },
      { item: "Onions", qty: 1, unit: "", category: "Fruit & veg" },
      { item: "Carrots", qty: 1, unit: "", category: "Fruit & veg" },
      { item: "Red peppers", qty: 1, unit: "", category: "Fruit & veg" },
      { item: "Garlic cloves", qty: 2, unit: "", category: "Fruit & veg" },
      { item: "Limes", qty: 1, unit: "", category: "Fruit & veg" },
      { item: "Chopped tomatoes", qty: 1, unit: "400 g tin", category: "Tins & jars" },
      { item: "Sweetcorn", qty: 100, unit: "g", category: "Tins & jars" },
      { item: "Basmati rice", qty: 250, unit: "g", category: "Pasta, rice & grains" },
      { item: "Chicken stock", qty: 450, unit: "ml", category: "Pantry" },
      { item: "Tomato purée", qty: 1, unit: "tbsp", category: "Pantry" },
      { item: "Grated cheese", qty: 100, unit: "g", category: "Dairy & eggs" },
      { item: "Smoked paprika", qty: 2, unit: "tsp", category: "Herbs & spices" },
      { item: "Ground cumin", qty: 1, unit: "tsp", category: "Herbs & spices" }
    ],
    method: [
      "Simmer the carrot and red pepper in the chopped tomatoes for 8 minutes, then blend smooth with the garlic and tomato purée.",
      "In a wide lidded pan, brown the chicken with the paprika and cumin. Add the onion and cook for another 3 minutes.",
      "Stir in the rice, blended tomato sauce and stock. Bring to a simmer, cover and cook gently for 18 minutes.",
      "Stir in the sweetcorn and cook for 3 to 4 minutes more. Finish with lime juice and a little grated cheddar."
    ],
    note: "This is deliberately smoother than normal fajita rice. The pepper and carrot disappear into the sauce rather than sitting around looking suspicious."
  },
  {
    id: "sticky-soy-chicken-rice",
    title: "Sticky Soy Chicken & Rice",
    summary: "Sweet-savoury chicken, glossy rice and stealth grated veg in one pan. Mild enough for the family, chilli oil optional for adults.",
    category: "One-pot",
    tags: ["Chicken", "One-pot", "Rice", "Hidden veg", "School night", "Asian-style"],
    serves: "4",
    prep: "15 mins",
    cook: "30 mins",
    made: false,
    archive: false,
    photo: "",
    photoAlt: "Sticky soy chicken and rice",
    photoStatus: "Ready to try",
    ingredients: [
      "600 g boneless chicken thighs or breast, diced",
      "2 tbsp low-salt soy sauce",
      "1 tbsp honey",
      "1 tbsp hoisin sauce",
      "1 tsp sesame oil",
      "2 garlic cloves, grated",
      "1 tsp grated ginger",
      "1 carrot, finely grated",
      "1 small courgette, finely grated",
      "250 g jasmine rice, rinsed",
      "550 ml chicken stock",
      "2 spring onions, sliced",
      "Sesame seeds, optional"
    ],
    shopping: [
      { item: "Chicken thighs", qty: 600, unit: "g", category: "Meat & fish" },
      { item: "Garlic cloves", qty: 2, unit: "", category: "Fruit & veg" },
      { item: "Fresh ginger", qty: 1, unit: "piece", category: "Fruit & veg" },
      { item: "Carrots", qty: 1, unit: "", category: "Fruit & veg" },
      { item: "Courgettes", qty: 1, unit: "", category: "Fruit & veg" },
      { item: "Spring onions", qty: 2, unit: "", category: "Fruit & veg" },
      { item: "Jasmine rice", qty: 250, unit: "g", category: "Pasta, rice & grains" },
      { item: "Chicken stock", qty: 550, unit: "ml", category: "Pantry" },
      { item: "Low-salt soy sauce", qty: 2, unit: "tbsp", category: "Pantry" },
      { item: "Honey", qty: 1, unit: "tbsp", category: "Pantry" },
      { item: "Hoisin sauce", qty: 1, unit: "tbsp", category: "Pantry" },
      { item: "Sesame oil", qty: 1, unit: "tsp", category: "Pantry" }
    ],
    method: [
      "Mix the soy, honey, hoisin and sesame oil. Toss half with the chicken.",
      "Brown the chicken in a wide lidded pan. Add garlic, ginger, carrot and courgette and cook for 3 to 4 minutes.",
      "Add the rice and stock. Cover and simmer gently for about 18 minutes.",
      "Stir through the remaining sauce, check the chicken and rice are cooked, then rest off the heat for 5 minutes.",
      "Scatter with spring onions and sesame seeds. Keep chilli oil on the table for anyone who wants to turn the volume up."
    ],
    note: "The grated vegetables melt into the rice and sauce. If courgette is especially watery, squeeze it lightly before adding."
  },
  {
    id: "hidden-veg-chicken-tomato-orzo",
    title: "Chicken Tomato Orzo with Hidden Veg",
    summary: "A spoonable one-pan chicken and orzo dinner with a smooth tomato sauce carrying carrot, courgette and pepper under the radar.",
    category: "One-pot",
    tags: ["Chicken", "One-pot", "Pasta", "Hidden veg", "School night"],
    serves: "4",
    prep: "15 mins",
    cook: "30 mins",
    made: false,
    archive: false,
    photo: "",
    photoAlt: "Chicken tomato orzo",
    photoStatus: "Ready to try",
    ingredients: [
      "600 g chicken breast, diced",
      "1 onion, chopped",
      "1 carrot, chopped",
      "1 small courgette, chopped",
      "1 red pepper, chopped",
      "2 garlic cloves",
      "1 x 400 g tin chopped tomatoes",
      "1 tbsp tomato purée",
      "300 g orzo",
      "650 ml chicken stock",
      "1 tsp dried oregano",
      "50 g Parmesan",
      "Handful baby spinach, optional"
    ],
    shopping: [
      { item: "Chicken breast", qty: 600, unit: "g", category: "Meat & fish" },
      { item: "Onions", qty: 1, unit: "", category: "Fruit & veg" },
      { item: "Carrots", qty: 1, unit: "", category: "Fruit & veg" },
      { item: "Courgettes", qty: 1, unit: "", category: "Fruit & veg" },
      { item: "Red peppers", qty: 1, unit: "", category: "Fruit & veg" },
      { item: "Garlic cloves", qty: 2, unit: "", category: "Fruit & veg" },
      { item: "Baby spinach", qty: 80, unit: "g", category: "Fruit & veg" },
      { item: "Chopped tomatoes", qty: 1, unit: "400 g tin", category: "Tins & jars" },
      { item: "Orzo", qty: 300, unit: "g", category: "Pasta, rice & grains" },
      { item: "Chicken stock", qty: 650, unit: "ml", category: "Pantry" },
      { item: "Tomato purée", qty: 1, unit: "tbsp", category: "Pantry" },
      { item: "Parmesan", qty: 50, unit: "g", category: "Dairy & eggs" },
      { item: "Dried oregano", qty: 1, unit: "tsp", category: "Herbs & spices" }
    ],
    method: [
      "Cook the onion, carrot, courgette, pepper and garlic with a splash of oil for 8 to 10 minutes until soft. Add the tomatoes and tomato purée, then blend smooth.",
      "Brown the chicken in the same pan with oregano, salt and pepper.",
      "Pour the smooth sauce back in, add orzo and stock, then simmer for 12 to 15 minutes, stirring regularly so the orzo does not catch.",
      "When the chicken and orzo are cooked, stir in Parmesan and spinach if using. Rest for 3 minutes before serving."
    ],
    note: "Make a double batch of the smooth veg sauce and freeze half. It can become emergency pasta sauce, pizza sauce or the base of another rice pot."
  },
  {
    id: "hidden-veg-beef-bolognese",
    title: "Proper Hidden-Veg Beef Bolognese",
    summary: "A beef-first Bolognese with carrot, courgette and mushrooms blended into the tomato sauce. Freezer-friendly and very difficult for children to interrogate.",
    category: "Pasta",
    tags: ["Beef", "Pasta", "Hidden veg", "Family dinner", "Freezer"],
    serves: "6",
    prep: "20 mins",
    cook: "1 hour",
    made: false,
    archive: false,
    photo: "",
    photoAlt: "Hidden vegetable beef bolognese",
    photoStatus: "Ready to try",
    ingredients: [
      "750 g beef mince",
      "1 onion, chopped",
      "2 carrots, chopped",
      "1 courgette, chopped",
      "150 g mushrooms, chopped",
      "3 garlic cloves",
      "2 tbsp tomato purée",
      "2 x 400 g tins chopped tomatoes",
      "250 ml beef stock",
      "1 tsp dried oregano",
      "1 tbsp Worcestershire sauce",
      "500 g spaghetti",
      "Parmesan to serve"
    ],
    shopping: [
      { item: "Beef mince", qty: 750, unit: "g", category: "Meat & fish" },
      { item: "Onions", qty: 1, unit: "", category: "Fruit & veg" },
      { item: "Carrots", qty: 2, unit: "", category: "Fruit & veg" },
      { item: "Courgettes", qty: 1, unit: "", category: "Fruit & veg" },
      { item: "Mushrooms", qty: 150, unit: "g", category: "Fruit & veg" },
      { item: "Garlic cloves", qty: 3, unit: "", category: "Fruit & veg" },
      { item: "Chopped tomatoes", qty: 2, unit: "400 g tin", category: "Tins & jars" },
      { item: "Spaghetti", qty: 500, unit: "g", category: "Pasta, rice & grains" },
      { item: "Beef stock", qty: 250, unit: "ml", category: "Pantry" },
      { item: "Tomato purée", qty: 2, unit: "tbsp", category: "Pantry" },
      { item: "Worcestershire sauce", qty: 1, unit: "tbsp", category: "Pantry" },
      { item: "Parmesan", qty: 75, unit: "g", category: "Dairy & eggs" },
      { item: "Dried oregano", qty: 1, unit: "tsp", category: "Herbs & spices" }
    ],
    method: [
      "Brown the beef mince hard in a large casserole until properly coloured, then remove to a bowl.",
      "Cook onion, carrots, courgette, mushrooms and garlic for 10 minutes. Add tomato purée and cook for another minute.",
      "Add chopped tomatoes and half the stock. Simmer for 10 minutes, then blend the vegetable sauce completely smooth.",
      "Return the beef to the pan with the remaining stock, oregano and Worcestershire sauce. Simmer gently for 35 to 45 minutes.",
      "Cook the spaghetti, loosen the Bolognese with a splash of pasta water if needed, and finish with Parmesan."
    ],
    note: "This is a good double-batch candidate. The same sauce can later become lasagne, baked pasta or even a taco filling."
  },
  {
    id: "beef-taco-rice-skillet",
    title: "Beef Taco Rice Skillet",
    summary: "All the good bits of taco night in one pan: seasoned beef, tomato rice, corn and cheese, with carrot and courgette cooked into the base.",
    category: "One-pot",
    tags: ["Beef", "Fajitas & tacos", "One-pot", "Rice", "Hidden veg", "School night"],
    serves: "4",
    prep: "15 mins",
    cook: "30 mins",
    made: false,
    archive: false,
    photo: "",
    photoAlt: "Beef taco rice skillet",
    photoStatus: "Ready to try",
    ingredients: [
      "500 g beef mince",
      "1 onion, finely diced",
      "1 carrot, finely grated",
      "1 small courgette, finely grated",
      "2 garlic cloves",
      "2 tsp smoked paprika",
      "1 tsp ground cumin",
      "1 tbsp tomato purée",
      "1 x 400 g tin chopped tomatoes",
      "250 g long-grain rice, rinsed",
      "450 ml beef stock",
      "100 g sweetcorn",
      "100 g cheddar, grated",
      "Tortilla chips, lime and sour cream to serve"
    ],
    shopping: [
      { item: "Beef mince", qty: 500, unit: "g", category: "Meat & fish" },
      { item: "Onions", qty: 1, unit: "", category: "Fruit & veg" },
      { item: "Carrots", qty: 1, unit: "", category: "Fruit & veg" },
      { item: "Courgettes", qty: 1, unit: "", category: "Fruit & veg" },
      { item: "Garlic cloves", qty: 2, unit: "", category: "Fruit & veg" },
      { item: "Limes", qty: 1, unit: "", category: "Fruit & veg" },
      { item: "Chopped tomatoes", qty: 1, unit: "400 g tin", category: "Tins & jars" },
      { item: "Sweetcorn", qty: 100, unit: "g", category: "Tins & jars" },
      { item: "Long-grain rice", qty: 250, unit: "g", category: "Pasta, rice & grains" },
      { item: "Beef stock", qty: 450, unit: "ml", category: "Pantry" },
      { item: "Tomato purée", qty: 1, unit: "tbsp", category: "Pantry" },
      { item: "Cheddar", qty: 100, unit: "g", category: "Dairy & eggs" },
      { item: "Sour cream", qty: 1, unit: "tub", category: "Dairy & eggs" },
      { item: "Tortilla chips", qty: 1, unit: "bag", category: "Snacks" },
      { item: "Smoked paprika", qty: 2, unit: "tsp", category: "Herbs & spices" },
      { item: "Ground cumin", qty: 1, unit: "tsp", category: "Herbs & spices" }
    ],
    method: [
      "Brown the beef mince well, breaking it up as it cooks.",
      "Add onion, grated carrot, courgette and garlic. Cook until the grated vegetables have softened into the mince.",
      "Stir in paprika, cumin and tomato purée, then add tomatoes, rice and stock.",
      "Cover and simmer gently for 18 to 20 minutes, stirring once or twice, until the rice is cooked.",
      "Stir in sweetcorn, scatter over cheddar and cover for 2 minutes to melt. Serve with lime, sour cream and a few crushed tortilla chips."
    ],
    note: "This scratches the taco-night itch without needing six bowls on the table. Add jalapeños to the adult portions afterwards rather than starting a domestic incident."
  },
  {
    id: "hidden-veg-beef-chilli",
    title: "Hidden-Veg Beef Chilli",
    summary: "A rich beef chilli where carrot, courgette and mushrooms are blitzed into the tomato base. Mild in the pot, heat added at the table.",
    category: "One-pot",
    tags: ["Beef", "One-pot", "Hidden veg", "Rice", "Freezer", "School night"],
    serves: "6",
    prep: "20 mins",
    cook: "50 mins",
    made: false,
    archive: false,
    photo: "",
    photoAlt: "Hidden vegetable beef chilli",
    photoStatus: "Ready to try",
    ingredients: [
      "750 g beef mince",
      "1 onion",
      "2 carrots",
      "1 courgette",
      "150 g mushrooms",
      "3 garlic cloves",
      "2 tbsp tomato purée",
      "2 x 400 g tins chopped tomatoes",
      "1 x 400 g tin kidney beans, drained",
      "250 ml beef stock",
      "2 tsp ground cumin",
      "2 tsp smoked paprika",
      "1 tsp mild chilli powder",
      "Cooked rice, grated cheese and sour cream to serve"
    ],
    shopping: [
      { item: "Beef mince", qty: 750, unit: "g", category: "Meat & fish" },
      { item: "Onions", qty: 1, unit: "", category: "Fruit & veg" },
      { item: "Carrots", qty: 2, unit: "", category: "Fruit & veg" },
      { item: "Courgettes", qty: 1, unit: "", category: "Fruit & veg" },
      { item: "Mushrooms", qty: 150, unit: "g", category: "Fruit & veg" },
      { item: "Garlic cloves", qty: 3, unit: "", category: "Fruit & veg" },
      { item: "Chopped tomatoes", qty: 2, unit: "400 g tin", category: "Tins & jars" },
      { item: "Kidney beans", qty: 1, unit: "400 g tin", category: "Tins & jars" },
      { item: "Beef stock", qty: 250, unit: "ml", category: "Pantry" },
      { item: "Tomato purée", qty: 2, unit: "tbsp", category: "Pantry" },
      { item: "Ground cumin", qty: 2, unit: "tsp", category: "Herbs & spices" },
      { item: "Smoked paprika", qty: 2, unit: "tsp", category: "Herbs & spices" },
      { item: "Mild chilli powder", qty: 1, unit: "tsp", category: "Herbs & spices" },
      { item: "Long-grain rice", qty: 300, unit: "g", category: "Pasta, rice & grains" },
      { item: "Grated cheese", qty: 100, unit: "g", category: "Dairy & eggs" },
      { item: "Sour cream", qty: 1, unit: "tub", category: "Dairy & eggs" }
    ],
    method: [
      "Brown the beef mince until deeply coloured and remove from the pan.",
      "Cook the onion, carrots, courgette, mushrooms and garlic for 10 minutes. Add tomato purée, tomatoes and a splash of stock, simmer briefly, then blend smooth.",
      "Return the beef, add remaining stock, cumin, paprika and mild chilli powder, and simmer for 30 minutes.",
      "Stir in the kidney beans for the final 10 minutes. Keep the main pot mild and serve hot sauce or sliced chillies separately.",
      "Serve over rice with cheese and sour cream."
    ],
    note: "Excellent freezer insurance. Freeze in family-size or single portions and it becomes a future school-night favour to yourselves."
  },
  {
    id: "lamb-kofta-tomato-rice-pot",
    title: "Lamb Kofta Tomato Rice Pot",
    summary: "Spiced lamb koftas cooked over tomato rice, with grated carrot and courgette folded into the base. One pan, plenty of flavour.",
    category: "One-pot",
    tags: ["Lamb", "One-pot", "Rice", "Hidden veg", "School night"],
    serves: "4",
    prep: "20 mins",
    cook: "30 mins",
    made: false,
    archive: false,
    photo: "",
    photoAlt: "Lamb kofta tomato rice pot",
    photoStatus: "Ready to try",
    ingredients: [
      "500 g lamb mince",
      "1 tsp ground cumin",
      "1 tsp ground coriander",
      "1 tsp paprika",
      "1 onion, finely diced",
      "1 carrot, finely grated",
      "1 small courgette, finely grated",
      "2 garlic cloves",
      "1 x 400 g tin chopped tomatoes",
      "250 g basmati rice",
      "450 ml chicken or lamb stock",
      "75 g frozen peas",
      "Greek yogurt and lemon to serve"
    ],
    shopping: [
      { item: "Lamb mince", qty: 500, unit: "g", category: "Meat & fish" },
      { item: "Onions", qty: 1, unit: "", category: "Fruit & veg" },
      { item: "Carrots", qty: 1, unit: "", category: "Fruit & veg" },
      { item: "Courgettes", qty: 1, unit: "", category: "Fruit & veg" },
      { item: "Garlic cloves", qty: 2, unit: "", category: "Fruit & veg" },
      { item: "Lemons", qty: 1, unit: "", category: "Fruit & veg" },
      { item: "Frozen peas", qty: 75, unit: "g", category: "Frozen" },
      { item: "Chopped tomatoes", qty: 1, unit: "400 g tin", category: "Tins & jars" },
      { item: "Basmati rice", qty: 250, unit: "g", category: "Pasta, rice & grains" },
      { item: "Chicken or lamb stock", qty: 450, unit: "ml", category: "Pantry" },
      { item: "Greek yogurt", qty: 1, unit: "tub", category: "Dairy & eggs" },
      { item: "Ground cumin", qty: 1, unit: "tsp", category: "Herbs & spices" },
      { item: "Ground coriander", qty: 1, unit: "tsp", category: "Herbs & spices" },
      { item: "Paprika", qty: 1, unit: "tsp", category: "Herbs & spices" }
    ],
    method: [
      "Mix the lamb with cumin, coriander, paprika, salt and pepper. Roll into small koftas.",
      "Brown the koftas in a wide lidded pan, then remove.",
      "Cook onion, grated carrot, courgette and garlic for 5 minutes. Add tomatoes, rice and stock.",
      "Nestle the koftas into the rice, cover and simmer gently for about 18 minutes.",
      "Add peas for the final 3 minutes, then serve with yogurt and lemon."
    ],
    note: "Smaller koftas cook faster and are easier for children. The rice base also works with beef meatballs if lamb is not available."
  },
  {
    id: "greek-lamb-potato-traybake",
    title: "Greek-Style Lamb & Potato Traybake",
    summary: "Lamb, lemon, oregano and potatoes in one roasting tray. Midweek-friendly but substantial enough to feel like proper dinner.",
    category: "Traybake",
    tags: ["Lamb", "Traybake", "One-pan", "Family dinner", "Mediterranean"],
    serves: "4",
    prep: "15 mins",
    cook: "50 mins",
    made: false,
    archive: false,
    photo: "",
    photoAlt: "Greek style lamb and potato traybake",
    photoStatus: "Ready to try",
    ingredients: [
      "600 g diced lamb leg or lamb steaks, cut into chunks",
      "700 g baby potatoes, halved",
      "1 red onion, cut into wedges",
      "1 courgette, thickly sliced",
      "2 tbsp olive oil",
      "2 tsp dried oregano",
      "1 tsp paprika",
      "3 garlic cloves, crushed",
      "1 lemon",
      "100 g feta, optional"
    ],
    shopping: [
      { item: "Diced lamb", qty: 600, unit: "g", category: "Meat & fish" },
      { item: "Baby potatoes", qty: 700, unit: "g", category: "Fruit & veg" },
      { item: "Red onions", qty: 1, unit: "", category: "Fruit & veg" },
      { item: "Courgettes", qty: 1, unit: "", category: "Fruit & veg" },
      { item: "Garlic cloves", qty: 3, unit: "", category: "Fruit & veg" },
      { item: "Lemons", qty: 1, unit: "", category: "Fruit & veg" },
      { item: "Feta", qty: 100, unit: "g", category: "Dairy & eggs" },
      { item: "Dried oregano", qty: 2, unit: "tsp", category: "Herbs & spices" },
      { item: "Paprika", qty: 1, unit: "tsp", category: "Herbs & spices" }
    ],
    method: [
      "Heat the oven to 210°C. Toss the potatoes and onion with half the oil, oregano and seasoning. Roast for 20 minutes.",
      "Toss the lamb and courgette with the remaining oil, paprika, garlic and lemon zest.",
      "Add the lamb mixture to the tray, turn everything together and roast for another 20 to 25 minutes until the lamb is cooked to your liking and the potatoes are tender.",
      "Finish with lemon juice and feta if using."
    ],
    note: "If the boys reject courgette on sight, leave it in larger pieces for adults and serve peas or corn alongside for them. Not every vegetable battle needs to be fought on a Tuesday."
  },
  {
    id: "saturday-lemon-garlic-roast-chicken",
    title: "Saturday Lemon & Garlic Roast Chicken",
    summary: "The dependable Saturday roast: crisp-skinned chicken, lemon, garlic, proper roast potatoes and gravy from the tray.",
    category: "Roast",
    tags: ["Chicken", "Roast", "Saturday", "Family dinner"],
    serves: "4-6",
    prep: "20 mins",
    cook: "1 hour 30 mins",
    made: false,
    archive: false,
    photo: "",
    photoAlt: "Lemon garlic roast chicken",
    photoStatus: "Ready to try",
    ingredients: [
      "1 whole chicken, about 1.8 kg",
      "1 lemon, halved",
      "1 whole garlic bulb",
      "2 tsp dried thyme or mixed herbs",
      "1.2 kg potatoes",
      "3 carrots",
      "2 onions",
      "2 tbsp olive oil",
      "500 ml chicken stock for gravy",
      "1 tbsp plain flour",
      "Salt and black pepper"
    ],
    shopping: [
      { item: "Whole chicken", qty: 1, unit: "1.8 kg", category: "Meat & fish" },
      { item: "Potatoes", qty: 1200, unit: "g", category: "Fruit & veg" },
      { item: "Carrots", qty: 3, unit: "", category: "Fruit & veg" },
      { item: "Onions", qty: 2, unit: "", category: "Fruit & veg" },
      { item: "Lemons", qty: 1, unit: "", category: "Fruit & veg" },
      { item: "Garlic bulbs", qty: 1, unit: "", category: "Fruit & veg" },
      { item: "Chicken stock", qty: 500, unit: "ml", category: "Pantry" },
      { item: "Plain flour", qty: 1, unit: "tbsp", category: "Baking" },
      { item: "Dried thyme", qty: 2, unit: "tsp", category: "Herbs & spices" }
    ],
    method: [
      "Heat the oven to 200°C. Put the lemon halves and half the garlic bulb inside the chicken. Rub the skin with oil, herbs, salt and pepper.",
      "Parboil the potatoes for 8 minutes, drain and rough up the edges. Put them in a roasting tray with carrots, onions and the remaining garlic.",
      "Sit the chicken above or among the vegetables and roast for around 1 hour 20 minutes to 1 hour 30 minutes, depending on size, until safely cooked through. Rest the chicken for at least 15 minutes.",
      "For the gravy, spoon off excess fat, put the roasting tray over heat, stir in flour, then gradually add stock while scraping up the browned tray juices.",
      "Carve and serve with the roast vegetables and gravy."
    ],
    note: "The exact roasting time depends on the bird. Use a thermometer in the thickest part rather than trusting the clock or family impatience."
  },
  {
    id: "saturday-roast-beef-onion-gravy",
    title: "Saturday Roast Beef & Onion Gravy",
    summary: "A classic beef roast with deeply browned onions, roast potatoes and gravy. The Saturday option when chicken needs a week off.",
    category: "Roast",
    tags: ["Beef", "Roast", "Saturday", "Family dinner"],
    serves: "6",
    prep: "20 mins",
    cook: "1 hour 15 mins + resting",
    made: false,
    archive: false,
    photo: "",
    photoAlt: "Roast beef with onion gravy",
    photoStatus: "Ready to try",
    ingredients: [
      "1.5 kg beef roasting joint",
      "1.2 kg potatoes",
      "3 onions, cut into wedges",
      "3 carrots",
      "2 tbsp olive oil",
      "1 tsp mustard powder",
      "500 ml beef stock",
      "1 tbsp plain flour",
      "1 tsp Worcestershire sauce",
      "Salt and black pepper"
    ],
    shopping: [
      { item: "Beef roasting joint", qty: 1500, unit: "g", category: "Meat & fish" },
      { item: "Potatoes", qty: 1200, unit: "g", category: "Fruit & veg" },
      { item: "Onions", qty: 3, unit: "", category: "Fruit & veg" },
      { item: "Carrots", qty: 3, unit: "", category: "Fruit & veg" },
      { item: "Beef stock", qty: 500, unit: "ml", category: "Pantry" },
      { item: "Worcestershire sauce", qty: 1, unit: "tsp", category: "Pantry" },
      { item: "Plain flour", qty: 1, unit: "tbsp", category: "Baking" },
      { item: "Mustard powder", qty: 1, unit: "tsp", category: "Herbs & spices" }
    ],
    method: [
      "Take the beef out of the fridge 45 minutes before cooking. Heat the oven to 220°C.",
      "Rub the beef with oil, mustard powder, salt and pepper. Roast at 220°C for 20 minutes, then reduce to 180°C and continue until it reaches your preferred internal temperature.",
      "Roast the potatoes, onions and carrots alongside, giving the potatoes enough room to crisp.",
      "Rest the beef loosely covered for at least 20 minutes.",
      "Use the roasting juices and softened onions for gravy: stir flour into the tray, gradually add beef stock and Worcestershire sauce, then simmer until glossy."
    ],
    note: "Temperature beats guesswork with roast beef. Pull it a little before your target because it continues cooking while it rests."
  },
  {
    id: "saturday-slow-roast-lamb-shoulder",
    title: "Saturday Slow-Roast Lamb Shoulder",
    summary: "Garlic, rosemary and lemon lamb shoulder cooked until spoon-tender. A low-effort Saturday roast that rewards starting early.",
    category: "Roast",
    tags: ["Lamb", "Roast", "Saturday", "Slow roast", "Family dinner"],
    serves: "6",
    prep: "20 mins",
    cook: "4 hours",
    made: false,
    archive: false,
    photo: "",
    photoAlt: "Slow roast lamb shoulder",
    photoStatus: "Ready to try",
    ingredients: [
      "1 lamb shoulder, about 2 kg",
      "5 garlic cloves",
      "2 tsp dried rosemary or 3 fresh sprigs",
      "1 lemon",
      "2 onions, thickly sliced",
      "3 carrots, cut into chunks",
      "300 ml chicken or lamb stock",
      "1.2 kg potatoes",
      "2 tbsp olive oil",
      "Salt and black pepper"
    ],
    shopping: [
      { item: "Lamb shoulder", qty: 2000, unit: "g", category: "Meat & fish" },
      { item: "Garlic cloves", qty: 5, unit: "", category: "Fruit & veg" },
      { item: "Lemons", qty: 1, unit: "", category: "Fruit & veg" },
      { item: "Onions", qty: 2, unit: "", category: "Fruit & veg" },
      { item: "Carrots", qty: 3, unit: "", category: "Fruit & veg" },
      { item: "Potatoes", qty: 1200, unit: "g", category: "Fruit & veg" },
      { item: "Chicken or lamb stock", qty: 300, unit: "ml", category: "Pantry" },
      { item: "Rosemary", qty: 1, unit: "pack", category: "Herbs & spices" }
    ],
    method: [
      "Heat the oven to 160°C. Put the onions and carrots in a deep roasting dish and sit the lamb on top.",
      "Rub the lamb with oil, garlic, rosemary, lemon zest, salt and pepper. Pour the stock around, not over, the meat.",
      "Cover tightly and roast for about 3 hours. Uncover, increase the oven to 200°C and roast for another 35 to 45 minutes until deeply browned and tender.",
      "Rest the lamb for 20 minutes. Roast potatoes separately or add parboiled potatoes around the lamb for the final hour if the tray has room.",
      "Skim excess fat from the tray juices and reduce them for a simple gravy. Finish with lemon juice."
    ],
    note: "This is the roast for days when you want impressive results without hovering over the oven. Low and slow does most of the work."
  }
];
