window.RECIPES = [...(window.RECIPES || []),
  {
    id: "nandos-style-chicken-pittas",
    title: "Nando's-Style Chicken & Halloumi Pittas",
    summary: "Peri-peri chicken thighs, lemon-garlic aioli, crisp halloumi and lettuce packed into toasted pittas. A proper Friday-night fakeaway.",
    category: "Fakeaway",
    tags: ["Chicken", "Fakeaway", "Friday", "Family dinner", "Air fryer", "Pitta"],
    serves: "Flexible - 1 pitta per person",
    prep: "20 mins + marinating",
    cook: "20 mins",
    made: false,
    archive: false,
    photo: "",
    photoAlt: "Nando's-style chicken and halloumi pitta",
    photoStatus: "Ready to try",
    source: "Family recipe supplied as Nandos Chicken Pittas",
    ingredients: [
      "Chicken thighs",
      "Pitta breads",
      "Gem lettuce",
      "Mayonnaise",
      "About 8 garlic cloves",
      "Lemon juice",
      "Halloumi",
      "Nando's medium dry rub, or the homemade peri-peri rub below",
      "Olive oil",
      "Optional mango chutney for the halloumi",
      "Optional sides: tenderstem broccoli, corn on the cob and chips",
      "Homemade peri-peri rub: 3 tbsp paprika, smoked or regular",
      "1 tsp cayenne pepper, adjusted to taste",
      "2 tsp garlic granules or powder",
      "1 tsp onion granules or powder",
      "1 tsp ground cumin",
      "1 tsp dried oregano",
      "1 tsp brown sugar",
      "2 tsp salt",
      "½ tsp black pepper"
    ],
    shopping: [
      { item: "Chicken thighs", qty: null, unit: "", category: "Meat & fish" },
      { item: "Pitta breads", qty: null, unit: "", category: "Bakery" },
      { item: "Gem lettuce", qty: null, unit: "", category: "Fruit & veg" },
      { item: "Garlic cloves", qty: 8, unit: "", category: "Fruit & veg" },
      { item: "Lemons", qty: null, unit: "", category: "Fruit & veg" },
      { item: "Halloumi", qty: null, unit: "", category: "Dairy & eggs" },
      { item: "Mayonnaise", qty: null, unit: "", category: "Tins & jars" },
      { item: "Nando's medium dry rub", qty: null, unit: "", category: "Pantry" },
      { item: "Olive oil", qty: null, unit: "", category: "Pantry" },
      { item: "Mango chutney", qty: null, unit: "", category: "Tins & jars" },
      { item: "Paprika", qty: 3, unit: "tbsp", category: "Herbs & spices" },
      { item: "Cayenne pepper", qty: 1, unit: "tsp", category: "Herbs & spices" },
      { item: "Garlic granules", qty: 2, unit: "tsp", category: "Herbs & spices" },
      { item: "Onion granules", qty: 1, unit: "tsp", category: "Herbs & spices" },
      { item: "Ground cumin", qty: 1, unit: "tsp", category: "Herbs & spices" },
      { item: "Dried oregano", qty: 1, unit: "tsp", category: "Herbs & spices" },
      { item: "Brown sugar", qty: 1, unit: "tsp", category: "Pantry" },
      { item: "Salt", qty: 2, unit: "tsp", category: "Pantry" },
      { item: "Black pepper", qty: 0.5, unit: "tsp", category: "Herbs & spices" }
    ],
    method: [
      "The day before, or in the morning, coat the chicken thighs in the Nando's dry rub or homemade peri-peri rub with a little olive oil. Leave to marinate as long as possible, ideally overnight.",
      "For the aioli, finely grate the garlic into a small bowl, cover with lemon juice and leave for at least 1 hour.",
      "When ready to cook, drain the garlic so the infused lemon juice runs into the mayonnaise. Add the liquid gradually, tasting until the garlic-lemon-mayo balance is right.",
      "Brown the chicken in a frying pan, then transfer to the oven or air fryer and cook through completely.",
      "While the chicken cooks, fry the halloumi in the same pan until browned and crisp. For the optional extra hit, add a small dollop of mango chutney to the halloumi as it finishes.",
      "Separate the gem lettuce leaves and toast the pittas.",
      "Open each pitta and spread generously with the garlic aioli. Add one or two lettuce leaves, about two chicken thighs and two slices of halloumi.",
      "Serve as they are, or with tenderstem broccoli, corn on the cob and chips."
    ],
    note: "The source recipe does not give total quantities for the chicken, pittas, lettuce, mayo or halloumi, so those stay deliberately flexible in our database. The assembly guide suggests roughly 2 chicken thighs and 2 halloumi slices per pitta."
  }
];
